services:
  diarization-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_grpc_diarizer
    ports:
      - "50051:50051"
    environment:
      - HF_TOKEN=${HF_TOKEN}  # Передайте ваш реальный токен от Hugging Face
      - PYTHONUNBUFFERED=1     # Чтобы логи в консоли Docker отображались в реальном времени
    volumes:
      # Правильный путь для кэша моделей Hugging Face (WhisperX / PyAnnote)
      - ./hf_cache:/root/.cache/huggingface
      # Путь для кэша моделей PyTorch (SpeechBrain / EncoderClassifier)
      - ./torch_cache:/root/.cache/torch
    restart: unless-stopped